name: dropdown_wheel_picker
description: Flutter package for dropdown scrollable wheel picker
version: 0.0.1
repository: https://github.com/fanjin-z/dropdown_wheel_picker
homepage: https://fanjin.org

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
      sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
